steps:
  - name: maven:3-jdk-8
    id: mvntest
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    id: mvnpackage
    waitFor:
      - mvntest
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]              
            
  - name: gcr.io/cloud-builders/docker
    id: build-service
    waitFor:
      - mvnpackage
#    args: ["build", "-t", "gcr.io/$PROJECT_ID/addressbook:$build_num", "--build-arg=WAR_FILE=target/addressbook.war", "."]
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t gcr.io/$PROJECT_ID/${_CONTAINERNAME}:latest -t gcr.io/$PROJECT_ID/${_CONTAINERNAME}:$build_num .
        docker push gcr.io/$PROJECT_ID/${_CONTAINERNAME}:latest 
        docker push gcr.io/$PROJECT_ID/${_CONTAINERNAME}:$build_num
###images: ["gcr.io/$PROJECT_ID/${_CONTAINERNAME}"]

substitutions:
  _CONFIG_BUCKET: 'project2-363320_cloudbuild'
  _BUILD_NAME: 'source'

