steps:
  - name: maven:3-jdk-8
    id: mvntest
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    id: mvnpackage
    waitFor:
      - mvntest
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]              
            
  - name: gcr.io/cloud-builders/docker
    id: build-service
    waitFor:
      - mvnpackage
#    args: ["build", "-t", "gcr.io/$PROJECT_ID/addressbook", "--build-arg=WAR_FILE=target/addressbook.war", "."]
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t gcr.io/$PROJECT_ID/addressbook1:1.0 --build-arg GIT_COMMIT=$(git log -1 --format=%h) .
        docker push gcr.io/$PROJECT_ID/addressbook1:1.0
       
#Update the container image using kubectl set
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/${_DEPLOYMENTNAME}'
    - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    _PROJECT: project2-363320
    _ZONE: asia-south1-a
    _GKE_CLUSTER: addresbook
    
    #Repository Specific configuration
    _DEPLOYMENTNAME: addresbook
    _CONTAINERNAME: addresbook1   
    
    # change
    _VERSION: v1.0
###images: ["gcr.io/$PROJECT_ID/addressbook"]
##
