steps:
  - name: maven:3-jdk-8
    id: mvntest
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    id: mvnpackage
    waitFor:
      - mvntest
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]              
            
  - name: gcr.io/cloud-builders/docker
    id: build-service
    waitFor:
      - mvnpackage
#    args: ["build", "-t", "gcr.io/$PROJECT_ID/addressbook", "--build-arg=WAR_FILE=target/addressbook.war", "."]
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t addressbook1:1.0-$GIT_COMMIT .
        docker push addressbook1:1.0-$GIT_COMMIT 
##
