steps:
  - name: maven:3-jdk-8
    id: mvntest
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    id: mvnpackage
    waitFor:
      - mvntest
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]              
            
  - name: gcr.io/cloud-builders/docker
    id: build-service
    waitFor:
      - mvnpackage
#    args: ["build", "-t", "gcr.io/$PROJECT_ID/addressbook", "--build-arg=WAR_FILE=target/addressbook.war", "."]
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t gcr.io/$PROJECT_ID/addressbook1:1.0 --build-arg GIT_COMMIT=$(git log -1 --format=%h) .
        docker push gcr.io/$PROJECT_ID/addressbook1:1.0
       
 - name: 'gcr.io/cloud-builders/kubectl'
   id: Deploy
   args:
   - 'apply'
   - '-f'
   - 'addressbook_deploy.yaml'
   env:
   - 'CLOUDSDK_COMPUTE_REGION=us-central1'
   - 'CLOUDSDK_CONTAINER_CLUSTER=addressbook'

   ##
  
