steps:
  - name: maven:3-jdk-8
    id: mvntest
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    id: mvnpackage
    waitFor:
      - mvntest
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]                        
  - name: gcr.io/cloud-builders/docker
    id: build-service
    waitFor:
      - mvnpackage
#    args: ["build", "-t", "gcr.io/$PROJECT_ID/addressbook:$build_num", "--build-arg=JAR_FILE=target/addressbook.jar", "."]  -
    entrypoint: 'bash'
    args:
      - -c
      - |
        source .buildenv &&
        docker build -t gcr.io/$PROJECT_ID/addressbook1:latest -t gcr.io/$PROJECT_ID/addressbook1:$build_num .
        docker push gcr.io/$PROJECT_ID/addressbook1:latest 
        docker push gcr.io/$PROJECT_ID/addressbook1:$build_num       
  # Update the container image using kubectl set 
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - 'set'
    - 'image'
    - 'deployment/${_DEPLOYMENTNAME}'
    - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_BUILD_NAME}'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
###images: ["gcr.io/$PROJECT_ID/addressbook"]
